use_frameworks!

platform :ios, '13.0'

target 'razorpay-turbo-ui-pod_Example' do
  pod 'razorpay-turbo-custom', :git => 'https://github.com/razorpay/razorpay-turbo-custom.git', :branch => 'release/2.1.5'

  # target 'razorpay-turbo-ui-pod_Tests' do
  #   inherit! :search_paths

    
  # end
end
