use_frameworks!

platform :ios, '13.0'

target 'razorpay-turbo-ui-pod_Example' do
  pod 'razorpay-turbo-custom/autopay-ui', :git => 'https://github.com/razorpay/razorpay-turbo-custom.git', :branch => 'feat/turbo-autopay-ui'
end
